name: Nmap Static Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.check.outputs.latest_version }}
      skip_build: ${{ steps.check.outputs.skip_build }}
    steps:
      - name: Check latest Nmap version
        id: check
        run: |
          LATEST_VERSION=$(curl -s https://nmap.org/dist/ | grep -o 'nmap-[0-9.]\+\.tar\.bz2' | sort -V | tail -n 1 | sed 's/nmap-\(.*\)\.tar\.bz2/\1/')
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          if gh release view "v$LATEST_VERSION" &> /dev/null; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: check-version
    if: needs.check-version.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86, arm64, armv7]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libssh-dev libssh2-1-dev automake

      - name: Install cross-compilation tools
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-i686-linux-gnu g++-i686-linux-gnu

      - name: Download and build Nmap
        run: |
          LATEST_VERSION=${{ needs.check-version.outputs.latest_version }}
          wget https://nmap.org/dist/nmap-$LATEST_VERSION.tar.bz2
          tar -xjf nmap-$LATEST_VERSION.tar.bz2
          cd nmap-$LATEST_VERSION
          
          case "${{ matrix.arch }}" in
            arm64)
              export CC=aarch64-linux-gnu-gcc
              export CXX=aarch64-linux-gnu-g++
              HOST=aarch64-linux-gnu
              ;;
            armv7)
              export CC=arm-linux-gnueabihf-gcc
              export CXX=arm-linux-gnueabihf-g++
              HOST=arm-linux-gnueabihf
              ;;
            x86)
              export CC=i686-linux-gnu-gcc
              export CXX=i686-linux-gnu-g++
              HOST=i686-linux-gnu
              ;;
            *)
              export CC=gcc
              export CXX=g++
              HOST=x86_64-linux-gnu
              ;;
          esac

          ./configure --host=$HOST --without-nmap-update --enable-static --without-zenmap
          make static
          
          mkdir -p ../release
          cp nmap ../release/nmap-${{ matrix.arch }} || echo "nmap not built"
          cp ncat/ncat ../release/ncat-${{ matrix.arch }} || echo "ncat not built"
          cp nping/nping ../release/nping-${{ matrix.arch }} || echo "nping not built"
          cp ndiff/ndiff.py ../release/ndiff-${{ matrix.arch }} || echo "ndiff not built"
          
          cd ../release
          tar -czvf nmap-static-$LATEST_VERSION-linux-${{ matrix.arch }}.tar.gz *-${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmap-static-${{ matrix.arch }}
          path: release/nmap-static-${{ needs.check-version.outputs.latest_version }}-linux-${{ matrix.arch }}.tar.gz

  create-release:
    runs-on: ubuntu-latest
    needs: [check-version, build]
    if: needs.check-version.outputs.skip_build == 'false'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: List files
        run: find ./release -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check-version.outputs.latest_version }}
          name: Nmap Static Build v${{ needs.check-version.outputs.latest_version }}
          body: |
            Static build of Nmap v${{ needs.check-version.outputs.latest_version }} for Linux architectures.
            
            Built with: libssl, libssh, libssh2
            Compiled with: `./configure --without-nmap-update --enable-static --without-zenmap; make static`
          files: ./release/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
