name: Nmap Static Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libssh-dev libssh2-1-dev automake

      - name: Check latest Nmap version
        id: check-version
        run: |
          LATEST_VERSION=$(curl -s https://nmap.org/dist/ | grep -o 'nmap-[0-9.]\+\.tar\.bz2' | sort -V | tail -n 1 | sed 's/nmap-\(.*\)\.tar\.bz2/\1/')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          
          if gh release view "v$LATEST_VERSION" &> /dev/null; then
            echo "SKIP_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_BUILD=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and build Nmap
        if: env.SKIP_BUILD == 'false'
        run: |
          wget https://nmap.org/dist/nmap-$LATEST_VERSION.tar.bz2
          tar -xjf nmap-$LATEST_VERSION.tar.bz2
          cd nmap-$LATEST_VERSION
          ./configure --without-nmap-update --enable-static --without-zenmap
          make static
          
          mkdir -p ../release
          cp nmap ../release/
          cp ncat/ncat ../release/ || echo "ncat not built"
          cp nping/nping ../release/ || echo "nping not built"
          cp ndiff/ndiff.py ../release/ || echo "ndiff not built"
          
          cd ../release
          tar -czvf nmap-static-$LATEST_VERSION-linux-x64.tar.gz *

      - name: Create Release
        if: env.SKIP_BUILD == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.LATEST_VERSION }}
          name: Nmap Static Build v${{ env.LATEST_VERSION }}
          body: |
            Static build of Nmap v${{ env.LATEST_VERSION }} for Linux x64
            
            Built with: libssl, libssh, libssh2
            Compiled with: `./configure --without-nmap-update --enable-static --without-zenmap; make static`
          files: release/nmap-static-${{ env.LATEST_VERSION }}-linux-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
